post http://localhost:4000/users/register
Content-Type: application/json

{
  "firstName": "Moh",
  "lastName": "Moh",
  "email": "moh2@test.de",
  "password": "123456",
  "city": "Hamburg",
  "country": "Germany",
  "userName": "Moh-82"
}

###


put http://localhost:4000/users/624e9ae4882034612bc08eb9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGU5YWU0ODgyMDM0NjEyYmMwOGViOSIsImlhdCI6MTY1MDk2MTAzMX0.SfkJahktipbw1YYymhmlzq9KIROqY-vfPzt9FFv6uGU


{
  "visible": true,
  "sentRequest": [{"userId": "624d5c70adba58fdf3fe95f4"}],
  "receivedRequest": [{"userId": "62614e57545b5ca036e52881"}],
  "friendsList": [{"friendId": "62679d29dda06d67a9e1fdc0"}]
}


###


delete http://localhost:4000/users/624d3f2a9fc97d734768e091

###

post http://localhost:4000/users/login
Content-Type: application/json

{
  "userName": "Moh82",
  "password": "Dd12345!"
}

###


get http://localhost:4000/users/626a7adc4857f368b56a29b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmE3YWRjNDg1N2YzNjhiNTZhMjliMiIsInVzZXJOYW1lIjoiTW9oODIiLCJpYXQiOjE2NTE3NDMzNzd9.q83vyeFfWEy05yA6lU6gMuGTMFPzUjY3x3QB35CiHXE



###

get http://localhost:4000/users

###

post http://localhost:4000/budget
Content-Type: application/json

{
  "type": "Present",
  "value": 1299.99,
  "date": "2022-04-06",
  "category": "salary April",
  "description": "Mein Lohn von 1299.99 Euro",
  "user": "624d5c70adba58fdf3fe95f4"
}

###

put http://localhost:4000/budget/624d857753ac9ccd98d1aadb
Content-Type: application/json

{
  "type": "Income",
  "value": 299.99,
  "category": "salary",
  "description": "Mein Lohn von 299.99 Euro",
  "user": "624d3f2a9fc97d734768e091"
}

###

delete http://localhost:4000/budget/624d8862377ebc157cd9f39b


###


post http://localhost:4000/Seed-money
Content-Type: application/json

{
  "total": 800.00,
  "user": "624e9ae4882034612bc08eb9"
}

###

delete http://localhost:4000/seed-money/624ee4eb39bde8dc194ee57c


###

put http://localhost:4000/Seed-money/624ee57eebf507d8d6a09c53
Content-Type: application/json

{
  "total": 849.99,
  "user": "624e9ae4882034612bc08eb9"
}


###

post http://localhost:4000/friend
Content-Type: application/json

{
  "sentRequest": "626a7adc4857f368b56a29b2",
  "receivedRequest": "6270dde6e87b8eebd7d2d827",
  "status": false
}


###


delete http://localhost:4000/users/6270dde6e87b8eebd7d2d827


###

post http://localhost:4000/trip
Content-Type: application/json

{
  "tripName": "Hamburg",
  "startDate": "2022-04-07",
  "endDate": "2022-04-06",
  "participants": ["62614e57545b5ca036e52881", "626fde017a5c9f43b1857a88"],
  "description": "Wir fahren nach Amsterdam :)"
}


###

get http://localhost:4000/trip/6278e3eebf8154f4c3acfaca

###

get http://localhost:4000/users/62614e57545b5ca036e52881


###

delete http://localhost:4000/trip/6278f84143f940a57e731ec9

###

put http://localhost:4000/trip/6278f6ad7d7316b557285f37
Content-Type: application/json

{
  "tripName": "Amsterdam",
  "startDate": "2022-04-07",
  "endDate": "2022-04-10",
  "description": "Wir fahren nach Amsterdam :)"
}