post http://localhost:4000/users/register
Content-Type: application/json

{
  "firstName": "Moh",
  "lastName": "Moh",
  "email": "moh@test.de",
  "password": "123456",
  "city": "Hamburg",
  "country": "Germany",
  "userName": "Moh-82"
}


###

post http://localhost:4000/users/login
Content-Type: application/json

{
  "userName": "test2-UserName",
  "password": "12345678"
}

###

get http://localhost:4000/users/624ab22cedfba008a0afeb6d